### ISSUE TITLE
Error in app.py?

### ISSUE THREAD

**Issue by mconsidine** [smart-underworld/seestar_alp#326]
I ended up with at 500 server error at one point with the latest pull.  The terminal console suggested a problem with app.py code around line 387.

I see this block:
```
        else:
            results = err_extractor(value) if value else "Offline"
            if results["status"] == "error":
                return results
            if results["result"] == 0:
                return results
            else:
                return results["result"]
        return results
```
and based on code previous to this it would appear that refs like results["status"] should be results[devnum]["status"].  There appear to only be these three instances in this file.

Am I mistaken or am I running a noncompliant version of Python?

**Comment by mconsidine** [comment]
This was the output to terminal:
```$ python3 root_app.py
Startup Complete
2024-10-04 16:32:48 [FALCON] [ERROR] POST /1/command => Traceback (most recent call last):
  File "falcon/app.py", line 365, in falcon.app.App.__call__
  File "/media/matt/Third_1TB/seestar_alp_source/seestar_alp/front/app.py", line 1264, in on_post
    output = do_command(req, resp, telescope_id)
  File "/media/matt/Third_1TB/seestar_alp_source/seestar_alp/front/app.py", line 844, in do_command
    output = method_sync("pi_reboot", telescope_id)
  File "/media/matt/Third_1TB/seestar_alp_source/seestar_alp/front/app.py", line 387, in method_sync
    if results["status"] == "error":
TypeError: string indices must be integers

```

**Comment by bguthro** [comment]
This was addressed as part of this commit:
```
commit 55002dc223cb071c008d39770babf5edd50c4aa8
Author: Brian <bhauber@gmail.com>
Date:   Wed Oct 9 17:38:27 2024 -0500

    Added Event Status Panel to Commands Page
 ```
