### ISSUE TITLE
Live view stops during mosaic with non-standard image size

### ISSUE THREAD

**Issue by JoshRovero** [smart-underworld/seestar_alp#505]
During mosaic data collection, Live View fails on the last panel.  From that point on, Live View of images is dead, although messages continue to scroll in its small console window.  

Exception in thread ImagingReceiveStarThread.Seestar Alpha:
Traceback (most recent call last):
  File "threading.py", line 1075, in _bootstrap_inner
  File "threading.py", line 1012, in run
  File "protocols/imager.py", line 131, in receiving_thread_fn
  File "protocols/imager.py", line 171, in _run_receive_message
  File "protocols/imager.py", line 241, in handle_preview_frame
  File "protocols/imager.py", line 278, in convert_star_image
ValueError: cannot reshape array of size 2045300 into shape (1920,1080)

**Comment by bguthro** [comment]
closing out this stale issue. please re-test on current mainline code
