### ISSUE TITLE
KeyError: 'is_use_autofocus'

### ISSUE THREAD

**Issue by AK51** [smart-underworld/seestar_alp#53]
Hi,

I am using the newest stellarium 24.2 on window, everything works until
in Bruno, I tried "action-start_mosaic_j2000"
Thx
```
Received request: Action start_mosaic with params {'target_name': 'kai32_NGC2244', 'ra': '6h31m54.23s', 'dec': '+4d56m26.4s', 'is_j2000': True, 'is_use_lp_filter': True, 'session_time_sec': 3600, 'ra_num': 2, 'dec_num': 2, 'panel_overlap_percent': 20, 'gain': 80}
Seestar Alpha : playing sound...
Exception in thread Thread-4 (<lambda>):
Traceback (most recent call last):
  File "D:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Seestar\seestar_alp\device\seestar_device.py", line 782, in <lambda>
    self.scheduler_thread = threading.Thread(target=lambda: self.scheduler_thread_fn())
  File "E:\Seestar\seestar_alp\device\seestar_device.py", line 795, in scheduler_thread_fn
    self.start_mosaic_item(item['params'])
  File "E:\Seestar\seestar_alp\device\seestar_device.py", line 694, in start_mosaic_item
    is_use_autofocus = params['is_use_autofocus']
KeyError: 'is_use_autofocus'
```

**Comment by YungKC** [comment]
Acknowledged. Working on the fix.

**Comment by smart-underworld** [comment]
Should have been fixed now and merged into main.

**Comment by smart-underworld** [comment]
Fixed.

**Comment by erewhon** [comment]
issue should be resolved now.
