### ISSUE TITLE
2.3.5 can no longer import schedule files that it creates

### ISSUE THREAD

**Issue by JoshRovero** [smart-underworld/seestar_alp#546]
Create a schedule in Schedule (and Planning)
Import schedule.
Receive error

2024-12-30 18:11:24 [FALCON] [ERROR] POST /1/schedule/import => Traceback (most recent call last):
  File "falcon/app.py", line 365, in falcon.app.App.__call__
  File "app.py", line 1823, in on_post
  File "app.py", line 1287, in import_schedule
AttributeError: 'NoneType' object has no attribute 'strip'

**Comment by smart-underworld** [comment]
The schedule import and export is being revamped to use JSON as the
preferred format. This change will be merged to main in the very near
future.
