### ISSUE TITLE
"Can't move up any further" sound

### ISSUE THREAD

**Issue by AK51** [smart-underworld/seestar_alp#56]
Hi,

I followed the youtube and it worked yesterday. Thx  https://youtu.be/8ms9CGxm__0?si=u-c6ixm7GhudYvcY&t=941
But today, when I try the "action_start_up_sequence" in Bruno, the seestar said "can't move up any further". But the seestar just moved up a little, not even close to the top.
And I couldn't get the Stellarium to control the seestar even Seestar was connected in Stellarium... I could see the orange sign move, but not the Seestar itself...

Is there a problem of the seestar read the wrong angle? But I have turn off the seestar, let the seestar go back to the orginal pointing down position. Then, turn it on again, same problem....

Thx

```
verify datetime string:  {'method': 'pi_set_time', 'params': [{'year': 2024, 'mon': 7, 'day': 15, 'hour': 19, 'min': 55, 'sec': 52, 'time_zone': 'Asia/Shanghai'}]}
verify locaion string:  {'method': 'set_user_location', 'params': {'lon': xxxxx, 'lat': xxxxx, 'force': False}}
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  10
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  10
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  10
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  8
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  10
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  8
Received request: Action action_start_up_sequence with params {'lat': 40, 'lon': 40}
verify datetime string:  {'method': 'pi_set_time', 'params': [{'year': 2024, 'mon': 7, 'day': 15, 'hour': 19, 'min': 56, 'sec': 34, 'time_zone': 'Asia/Shanghai'}]}
verify locaion string:  {'method': 'set_user_location', 'params': {'lon': 40, 'lat': 40, 'force': False}}
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  10
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  10
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  10
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  8
Received request: Action action_start_up_sequence with params {'lat': 0, 'lon': 0}
Your current GPS coordinates are:
Latitude: xxxxx
Longitude: xxxxxx
verify datetime string:  {'method': 'pi_set_time', 'params': [{'year': 2024, 'mon': 7, 'day': 15, 'hour': 19, 'min': 58, 'sec': 44, 'time_zone': 'Asia/Shanghai'}]}
verify locaion string:  {'method': 'set_user_location', 'params': {'lon': xxxxxxx, 'lat': xxxxx, 'force': False}}
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  10
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  10
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  10
Received request: Action action_start_up_sequence with params {'lat': 10, 'lon': 10}
verify datetime string:  {'method': 'pi_set_time', 'params': [{'year': 2024, 'mon': 7, 'day': 15, 'hour': 19, 'min': 59, 'sec': 11, 'time_zone': 'Asia/Shanghai'}]}
verify locaion string:  {'method': 'set_user_location', 'params': {'lon': 10, 'lat': 10, 'force': False}}
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  10
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  8
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  10
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  10
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  8

```

**Comment by smart-underworld** [comment]
You can use the original Seestar app to try to move Seestar arm up. Does
this work? I have not encountered this issue, especially if the Seestar
starts from a cold boot up. Stellarrium sometimes will not reflect where
Seestar is aiming at the beginning (I think it's a bug in stellarrium)
until a few reconnects or after a few GoTo/sync.

**Comment by AK51** [comment]
I used the app to control te seestar. And then reboot the seestar, the "action_start_up_sequence" works ok now. But, the Stellarium still cannot make the seestar move.... 
This is the print out after I clicked "Sync" in Stellarium... I used the newest version and it worked yesterday. Will it be the version problem?I can't find your Stellarium version, where can I download it? Thx
```
Seestar Alpha : sync to target... 14.2803843759104 19.0573887738691 , with dec_offset of  0
```

```
Connected
Received request: Action action_start_up_sequence with params {'lat': 0, 'lon': 0}
Your current GPS coordinates are:
Latitude: xxxxx
Longitude: xxxxx
verify datetime string:  {'method': 'pi_set_time', 'params': [{'year': 2024, 'mon': 7, 'day': 15, 'hour': 20, 'min': 50, 'sec': 31, 'time_zone': 'Asia/Shanghai'}]}
verify locaion string:  {'method': 'set_user_location', 'params': {'lon': xxxx, 'lat': xxxx, 'force': False}}
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  10
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  10
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  10
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  8
Seestar Alpha : sync to target... 14.2803843759104 19.0573887738691 , with dec_offset of  0
```
<img width="804" alt="image" src="https://github.com/user-attachments/assets/7329c1ec-ceab-4841-b09f-f96c53a1bb1f">

**Comment by AK51** [comment]
When I click Slew, there is a voice says "Finding object" from Seestar
But why the seestar does not move  when I click "Sync"?
```
Goto Final State:  {'Event': 'AutoGoto', 'Timestamp': '1018.551045624', 'page': 'preview', 'tag': 'Exposure', 'func': 'goto_ra_dec', 'state': 'fail', 'error': 'aborted', 'code': 253}
Seestar Alpha : going to target... unknown 19.530271330255104 -13.4870933166484 , with dec offset  0
Seestar Alpha : stopping slew...
```

**Comment by AK51** [comment]
Happen again "Can't move up any further"

I click "action_start_up_sequence" again and it happened...
```
verify datetime string:  {'method': 'pi_set_time', 'params': [{'year': 2024, 'mon': 7, 'day': 15, 'hour': 21, 'min': 33, 'sec': 36, 'time_zone': 'Asia/Shanghai'}]}
verify locaion string:  {'method': 'set_user_location', 'params': {'lon': xxx, 'lat': xxx, 'force': False}}
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  10
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  10
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  10
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  8
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  10
Seestar Alpha : moving slew angle:  90 , speed:  1000 , dur:  8

```

<img width="1000" alt="image" src="https://github.com/user-attachments/assets/9def8795-3b05-4bb9-b0d3-d748df3a8160">

**Comment by AK51** [comment]
I find out the "action_start_up_sequence" can not click twice.
Anyway, I still cannot move the Seestar using stellarium.... It worked yesterday.... >_<

Btw, the error still exist... I have git pull before.
```
Received request: Action start_mosaic with params {'target_name': 'kai32_NGC2244', 'ra': -1.0, 'dec': -1.0, 'is_use_lp_filter': True, 'session_time_sec': 3600, 'ra_num': 1, 'dec_num': 1, 'panel_overlap_percent': 100, 'gain': 80}
Seestar Alpha : playing sound...
Exception in thread Thread-4 (<lambda>):
Traceback (most recent call last):
  File "D:\Python310\lib\threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "D:\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "E:\Seestar\seestar_alp\device\seestar_device.py", line 782, in <lambda>
    self.scheduler_thread = threading.Thread(target=lambda: self.scheduler_thread_fn())
  File "E:\Seestar\seestar_alp\device\seestar_device.py", line 795, in scheduler_thread_fn
    self.start_mosaic_item(item['params'])
  File "E:\Seestar\seestar_alp\device\seestar_device.py", line 694, in start_mosaic_item
    is_use_autofocus = params['is_use_autofocus']
KeyError: 'is_use_autofocus'


```

**Comment by YungKC** [comment]
The startup action is intended to move Seestar high up in preparation of EQ
mode, and thus is only meant to be done once ( it is named start up after
all ). If you tried twice, it can't go any higher and thus you get that
error.

**Comment by bguthro** [comment]
Closing out old issues. This one is very old
